#!/usr/bin/php
<?php
require_once './../helpers/functions.php';
require '../config/db.php';
require __DIR__ . '/../vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__.'/..');
$dotenv->load();

$title = "Remove Flight";

cli_set_process_title($title);

$code = $argv[1] ?? "";
if (empty($code)) {
    error('Code is required');
}

$pdo = dbConnect(DB_PATH);

if ($pdo === null) {
    error("Connection with database failed!");
}

require_once "../helpers/queries.php";

$removeData = deleteFlightInfo($pdo, $code);

if(!$removeData){
    error("Unable to delete flight with code: $code");
}
    info("Flight with code $code deleted successfully!");