#!/usr/bin/php
<?php
require_once './../helpers/functions.php';
require '../config/db.php';
require __DIR__ . '/../vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__.'/..');
$dotenv->load();
$title = "Import Flight Info";

cli_set_process_title($title);

$format = $argv[1] ?? "";
    if (empty($format)) {
        error('Format is required');
    }

$filePath = $argv[2] ?? "";
    if (empty($location)) {
        error('File path is required');
    }

$fileExtension = strtolower(pathinfo($filePath, PATHINFO_EXTENSION));

if(!in_array($fileExtension, ["csv", "xls", "json"])){
    error('Invalid file extension! Please use one of csv, xls, json extensions!');
}

$pdo = dbConnect(DB_PATH);

    if ($pdo === null) {
        error("Connection with database failed!");
    }

require_once "../helpers/queries.php";

