#!/usr/bin/php
<?php
require_once './../helpers/functions.php';
require '../config/db.php';
require __DIR__ . '/../vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__.'/..');
$dotenv->load();
$title = "Import Flight Info";

cli_set_process_title($title);

$format = $argv[1] ?? "";
    if (empty($format)) {
        error('Format is required');
    }

$filePath = $argv[2] ?? "";
    if (empty($location)) {
        error('File path is required');
    }

$fileExtension = strtolower(pathinfo($filePath, PATHINFO_EXTENSION));

if(!in_array($fileExtension, ["csv", "xls", "xlsx"])){
    error('Invalid file extension! Please use one of csv, xls, xlsx extensions!');
}

$pdo = dbConnect($_ENV["DB_HOST"], $_ENV["PORT"], $_ENV["DATABASE"], $_ENV["DB_USER"], $_ENV["DB_PASSWORD"]);

    if ($pdo === null) {
        error("Connection with database failed!");
    }

require_once "../helpers/queries.php";

